name: Deploy to Render
on:
    push:
        branches:
            - master
            # note that your "main" branch might be called main instead of master
    pull_request: // highlight-line
        branches: [master] // highlight-line
        types: [opened, synchronize] // highlight-line
jobs:
    deploy_to_render:
        runs-on: ubuntu-20.04
        steps:
            - name: Trigger deployment
              run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
